// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proxy} from '../models';

export function FrontPause():Promise<void>;

export function FrontResume():Promise<void>;

export function LogPrint(arg1:any):Promise<void>;

export function ProxyAddHost(arg1:string):Promise<void>;

export function ProxyCatchHosts():Promise<Array<string>>;

export function ProxyCloseCert():Promise<void>;

export function ProxyFlowClear():Promise<void>;

export function ProxyFlowListByPage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:boolean):Promise<Record<string, any>>;

export function ProxyHostList(arg1:boolean):Promise<Array<proxy.Option>>;

export function ProxyInfo():Promise<Record<string, any>>;

export function ProxyRemoteAddrs():Promise<Array<string>>;

export function ProxyRemoveHost(arg1:string):Promise<void>;

export function ProxyResetHost():Promise<void>;

export function ProxySaveCert():Promise<string>;

export function ProxyShowCert():Promise<string>;

export function ProxyStart():Promise<void>;

export function ProxyStop():Promise<void>;

export function WindowGetHeight():Promise<number>;

export function WindowGetWidth():Promise<number>;
