// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FrontPause() {
  return window['go']['apps']['App']['FrontPause']();
}

export function FrontResume() {
  return window['go']['apps']['App']['FrontResume']();
}

export function LogPrint(arg1) {
  return window['go']['apps']['App']['LogPrint'](arg1);
}

export function ProxyAddHost(arg1) {
  return window['go']['apps']['App']['ProxyAddHost'](arg1);
}

export function ProxyCatchHosts() {
  return window['go']['apps']['App']['ProxyCatchHosts']();
}

export function ProxyCloseCert() {
  return window['go']['apps']['App']['ProxyCloseCert']();
}

export function ProxyFlowClear() {
  return window['go']['apps']['App']['ProxyFlowClear']();
}

export function ProxyFlowListByPage(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['apps']['App']['ProxyFlowListByPage'](arg1, arg2, arg3, arg4, arg5);
}

export function ProxyHostList(arg1) {
  return window['go']['apps']['App']['ProxyHostList'](arg1);
}

export function ProxyInfo() {
  return window['go']['apps']['App']['ProxyInfo']();
}

export function ProxyRemoteAddrs() {
  return window['go']['apps']['App']['ProxyRemoteAddrs']();
}

export function ProxyRemoveHost(arg1) {
  return window['go']['apps']['App']['ProxyRemoveHost'](arg1);
}

export function ProxyResetHost() {
  return window['go']['apps']['App']['ProxyResetHost']();
}

export function ProxySaveCert() {
  return window['go']['apps']['App']['ProxySaveCert']();
}

export function ProxyShowCert() {
  return window['go']['apps']['App']['ProxyShowCert']();
}

export function ProxyStart() {
  return window['go']['apps']['App']['ProxyStart']();
}

export function ProxyStop() {
  return window['go']['apps']['App']['ProxyStop']();
}

export function WindowGetHeight() {
  return window['go']['apps']['App']['WindowGetHeight']();
}

export function WindowGetWidth() {
  return window['go']['apps']['App']['WindowGetWidth']();
}
